language: python

python:
  - "3.6"

services: mysql

env:
  global:
    - DJANGO_SETTINGS_MODULE="ujumbe.settings"
    - PYTHONPATH="/home/travis/build/jerryshikanga/ujumbe"
    - PIP_USE_MIRRORS=true
    - BUILD_ON_TRAVIS=true
  matrix:
    - DJANGO=2.1.1 DB=mysql

#commands to install dependencies
install:
  - pip install -q -r requirements.txt

before_script:
  - mysql -e "CREATE DATABASE ujumbe; CREATE USER 'ujumbe'@'localhost' IDENTIFIED BY 'ujumbe'; GRANT ALL PRIVILEGES ON * . * TO 'ujumbe'@'localhost'; FLUSH PRIVILEGES;"
  - python manage.py makemigrations

#command to run the test suite
script:
  - python manage.py test