# Generated by Django 2.1.1 on 2019-08-01 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketdata', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productprice',
            name='quantity',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
