# Generated by Django 2.1.1 on 2019-08-01 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketdata', '0002_auto_20190801_2112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productprice',
            name='currency_code',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='productprice',
            name='measurement_unit',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='productprice',
            name='price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
