# Generated by Django 2.1.1 on 2019-08-01 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketdata', '0003_auto_20190801_2114'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productprice',
            old_name='price',
            new_name='high_price',
        ),
        migrations.AddField(
            model_name='productprice',
            name='low_price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
