# Generated by Django 2.1.1 on 2018-10-28 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_accountcharges_cuurency_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accountcharges',
            old_name='cuurency_code',
            new_name='currency_code',
        ),
    ]
