# Generated by Django 2.1.1 on 2018-10-28 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_auto_20181028_1912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountcharges',
            name='cost',
            field=models.DecimalField(decimal_places=10, max_digits=10),
        ),
    ]
