# Generated by Django 2.1.1 on 2019-01-23 16:44

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_auto_20181107_0745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='telephone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, unique=True),
        ),
    ]
