# Generated by Django 2.1.1 on 2018-10-03 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather_data', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='currentlocationweather',
            name='description',
        ),
    ]
