# Generated by Django 2.1.1 on 2018-10-04 15:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IncomingMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('phonenumber', models.CharField(max_length=20)),
                ('text', models.CharField(max_length=255)),
                ('handler', models.CharField(choices=[('Africastalking', 'Africastalking'), ('Nexmo', 'Nexmo')], default='Africastalking', max_length=100)),
                ('africastalking_id', models.CharField(max_length=255)),
                ('link_id', models.CharField(blank=True, max_length=255, null=True)),
                ('shortcode', models.CharField(max_length=10)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OutgoingMessages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('phonenumber', models.CharField(max_length=20)),
                ('text', models.CharField(max_length=255)),
                ('handler', models.CharField(choices=[('Africastalking', 'Africastalking'), ('Nexmo', 'Nexmo')], default='Africastalking', max_length=100)),
                ('cost', models.CharField(default='', max_length=10)),
                ('delivery_status', models.CharField(choices=[('failed', 'Failed'), ('Sent', 'Sent'), ('Delivered', 'Delivered'), ('Unknown', 'Unknown')], default='UNKNOWN', max_length=20)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outgoingmessages_create', to=settings.AUTH_USER_MODEL, verbose_name='author')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outgoingmessages_update', to=settings.AUTH_USER_MODEL, verbose_name='last updated by')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
