# Generated by Django 2.1.1 on 2018-10-28 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('africastalking', '0004_auto_20181020_2152'),
    ]

    operations = [
        migrations.RenameField(
            model_name='incomingmessage',
            old_name='africastalking_id',
            new_name='provider_id',
        ),
        migrations.AddField(
            model_name='outgoingmessages',
            name='provider_id',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='incomingmessage',
            name='handler',
            field=models.CharField(choices=[('Africastalking', 'Africastalking'), ('Nexmo', 'Nexmo')], max_length=100),
        ),
        migrations.AlterField(
            model_name='outgoingmessages',
            name='handler',
            field=models.CharField(choices=[('Africastalking', 'Africastalking'), ('Nexmo', 'Nexmo')], max_length=100),
        ),
    ]
