# Generated by Django 2.1.1 on 2019-01-16 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('africastalking', '0007_auto_20181028_1915'),
    ]

    operations = [
        migrations.AddField(
            model_name='incomingmessage',
            name='processed',
            field=models.BooleanField(default=False),
        ),
    ]
