# Generated by Django 2.1.1 on 2019-01-18 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('africastalking', '0008_incomingmessage_processed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incomingmessage',
            name='handler',
            field=models.CharField(choices=[('Africastalking', 'Africastalking'), ('Nexmo', 'Nexmo'), ('Telerivet', 'Telerevivet')], max_length=100),
        ),
        migrations.AlterField(
            model_name='incomingmessage',
            name='shortcode',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='outgoingmessages',
            name='handler',
            field=models.CharField(choices=[('Africastalking', 'Africastalking'), ('Nexmo', 'Nexmo'), ('Telerivet', 'Telerevivet')], max_length=100),
        ),
    ]
