# Generated by Django 2.1.1 on 2019-01-18 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('africastalking', '0009_auto_20190118_0004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incomingmessage',
            name='handler',
            field=models.CharField(choices=[('Africastalking', 'Africastalking'), ('Nexmo', 'Nexmo'), ('Telerivet', 'Telerivet')], max_length=100),
        ),
        migrations.AlterField(
            model_name='outgoingmessages',
            name='handler',
            field=models.CharField(choices=[('Africastalking', 'Africastalking'), ('Nexmo', 'Nexmo'), ('Telerivet', 'Telerivet')], max_length=100),
        ),
    ]
