# Generated by Django 2.1.1 on 2019-01-24 12:39

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('africastalking', '0010_auto_20190118_2242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incomingmessage',
            name='phonenumber',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128),
        ),
        migrations.AlterField(
            model_name='outgoingmessages',
            name='phonenumber',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128),
        ),
    ]
