# Generated by Django 2.1.1 on 2019-01-24 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('africastalking', '0011_auto_20190124_1239'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incomingmessage',
            name='link_id',
        ),
        migrations.AddField(
            model_name='incomingmessage',
            name='datetime_sent',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
