# Generated by Django 2.1.1 on 2019-02-04 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('africastalking', '0012_auto_20190124_1324'),
    ]

    operations = [
        migrations.AddField(
            model_name='incomingmessage',
            name='response',
            field=models.TextField(blank=True, null=True),
        ),
    ]
