# Generated by Django 2.1.1 on 2018-09-26 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ussd_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ussdsession',
            old_name='msisdn',
            new_name='phone_number',
        ),
        migrations.AlterField(
            model_name='ussdsession',
            name='current_step',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
