# Generated by Django 2.1.1 on 2018-10-04 15:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrentWeather',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('summary', models.CharField(default='', max_length=255)),
                ('temperature', models.IntegerField(default=0)),
                ('pressure', models.IntegerField(default=0)),
                ('humidity', models.IntegerField(default=0)),
                ('temp_min', models.IntegerField(default=0)),
                ('temp_max', models.IntegerField(default=0)),
                ('visibility', models.IntegerField(default=0)),
                ('wind_speed', models.IntegerField(default=0)),
                ('wind_degree', models.IntegerField(default=0)),
                ('clouds_all', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Current Weather',
                'verbose_name_plural': 'Current Weather',
            },
        ),
        migrations.CreateModel(
            name='ForecastWeather',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('summary', models.CharField(default='', max_length=255)),
                ('temperature', models.IntegerField(default=0)),
                ('pressure', models.IntegerField(default=0)),
                ('humidity', models.IntegerField(default=0)),
                ('temp_min', models.IntegerField(default=0)),
                ('temp_max', models.IntegerField(default=0)),
                ('visibility', models.IntegerField(default=0)),
                ('wind_speed', models.IntegerField(default=0)),
                ('wind_degree', models.IntegerField(default=0)),
                ('clouds_all', models.IntegerField(default=0)),
                ('period', models.DurationField()),
            ],
            options={
                'verbose_name': 'Forecast Weather',
                'verbose_name_plural': 'Forecast Weather',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('latitude', models.FloatField(default=0)),
                ('longitude', models.FloatField(default=0)),
                ('name', models.CharField(choices=[('Mombasa', 'Mombasa'), ('Isiolo', 'Isiolo'), ("Murang'a", 'Muranga'), ('Laikipia', 'Laikipi'), ('Siaya', 'Siaya'), ('Kwale', 'Kwale'), ('Meru', 'Meru'), ('Kiambu', 'Kiambu'), ('Nakuru', 'Nakuru'), ('Kisumu', 'Kisumu'), ('Kilifi', 'Kilifi'), ('Tharaka-Nithi', 'TharakaNithi'), ('Turkana', 'Turkana'), ('Narok', 'Narok'), ('homa-Bay', 'HomaBay'), ('Tana-River', 'TanaRiver'), ('Embu', 'Embu'), ('West-Pokot', 'WestPokot'), ('Kajiado', 'Kajiado'), ('Migori', 'Migori'), ('Lamu', 'Lamu'), ('Kitui', 'Kitui'), ('Samburu', 'Samburu'), ('Kericho', 'Kericho'), ('Kisii', 'Kisii'), ('Taita-Taveta', 'TaitaTaveta'), ('Machakos', 'Machakos'), ('Trans-Nzoia', 'TransNzoia'), ('Bomet', 'Bomet'), ('Nyamira', 'Nyamira'), ('Garissa', 'Garissa'), ('Makueni', 'Makueni'), ('UasinGishu', 'UasinGishu'), ('Kakamega', 'Kakamega'), ('Nairobi', 'Nairobi'), ('Wajir', 'Wajir'), ('Nyandarua', 'Nyandarua'), ('Elgeyo-Marakwet', 'ElgeyoMarakwet'), ('Vihiga', 'Vihiga'), ('Mandera', 'Mandera'), ('Nyeri', 'Nyeri'), ('Nandi', 'Nandi'), ('Bungoma', 'Bungoma'), ('Marsabit', 'Marsabit'), ('Kirinyaga', 'Kirinyaga'), ('Baringo', 'Baringo'), ('Busia', 'Busia')], max_length=255)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='location_create', to=settings.AUTH_USER_MODEL, verbose_name='author')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='location_update', to=settings.AUTH_USER_MODEL, verbose_name='last updated by')),
            ],
            options={
                'ordering': ('-modified', '-created'),
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='forecastweather',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='weather.Location'),
        ),
        migrations.AddField(
            model_name='currentweather',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='weather.Location'),
        ),
    ]
