# Generated by Django 2.1.1 on 2018-10-11 22:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0002_auto_20181006_1416'),
    ]

    operations = [
        migrations.AddField(
            model_name='currentweather',
            name='rain',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='forecastweather',
            name='forecast_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='forecastweather',
            name='rain',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='owm_city_id',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='owm_details_set',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='currentweather',
            name='visibility',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='forecastweather',
            name='visibility',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
