# Generated by Django 2.1.1 on 2018-11-24 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0005_auto_20181020_2200'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='lat_ne',
            new_name='bounds_northeast_latitude',
        ),
        migrations.RenameField(
            model_name='location',
            old_name='lat_sw',
            new_name='bounds_northeast_longitude',
        ),
        migrations.RenameField(
            model_name='location',
            old_name='lon_ne',
            new_name='bounds_southwest_latitude',
        ),
        migrations.RenameField(
            model_name='location',
            old_name='lon_sw',
            new_name='bounds_southwest_longitude',
        ),
        migrations.RemoveField(
            model_name='location',
            name='owm_details_set',
        ),
        migrations.AddField(
            model_name='location',
            name='googlemaps_place_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
