# Generated by Django 2.1.1 on 2018-11-25 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0006_auto_20181124_2133'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forecastweather',
            name='period',
        ),
        migrations.AddField(
            model_name='forecastweather',
            name='days',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='location',
            name='accuweather_city_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='currentweather',
            name='handler',
            field=models.CharField(choices=[('NETATMO', 'netatmo'), ('OPENWEATHER', 'openweather'), ('AccuWeather', 'accuweather')], max_length=30),
        ),
        migrations.AlterField(
            model_name='forecastweather',
            name='handler',
            field=models.CharField(choices=[('NETATMO', 'netatmo'), ('OPENWEATHER', 'openweather'), ('AccuWeather', 'accuweather')], max_length=30),
        ),
    ]
