# Generated by Django 2.1.1 on 2019-07-28 22:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncomingMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('phonenumber', phonenumber_field.modelfields.PhoneNumberField(max_length=128)),
                ('processed', models.BooleanField(default=False)),
                ('text', models.TextField()),
                ('handler', models.CharField(choices=[('Africastalking', 'Africastalking'), ('Nexmo', 'Nexmo'), ('Telerivet', 'Telerivet')], max_length=100)),
                ('provider_id', models.CharField(max_length=255)),
                ('datetime_sent', models.DateTimeField(blank=True, null=True)),
                ('shortcode', models.CharField(max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OutgoingMessages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('phonenumber', phonenumber_field.modelfields.PhoneNumberField(max_length=128)),
                ('processed', models.BooleanField(default=False)),
                ('text', models.TextField()),
                ('handler', models.CharField(choices=[('Africastalking', 'Africastalking'), ('Nexmo', 'Nexmo'), ('Telerivet', 'Telerivet')], max_length=100)),
                ('provider_id', models.CharField(max_length=255)),
                ('delivery_status', models.CharField(choices=[('Failed', 'failed'), ('Sent', 'sent'), ('Delivered', 'Delivered'), ('Submitted', 'submitted'), ('Buffered', 'buffered'), ('Rejected', 'rejected'), ('Success', 'success')], default='Submitted', max_length=50)),
                ('failure_reason', models.CharField(blank=True, max_length=50, null=True)),
                ('translated_text', models.TextField()),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outgoingmessages_create', to=settings.AUTH_USER_MODEL, verbose_name='author')),
                ('charge', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='profiles.AccountCharges')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outgoingmessages_update', to=settings.AUTH_USER_MODEL, verbose_name='last updated by')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UssdSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('session_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('phonenumber', models.CharField(blank=True, max_length=34, null=True)),
                ('service_code', models.CharField(blank=True, max_length=10, null=True)),
                ('text', models.TextField(blank=True, null=True)),
                ('last_response', models.TextField(blank=True, null=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ussdsession_create', to=settings.AUTH_USER_MODEL, verbose_name='author')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ussdsession_update', to=settings.AUTH_USER_MODEL, verbose_name='last updated by')),
            ],
            options={
                'verbose_name': 'Ussd Session',
                'verbose_name_plural': 'Ussd Sessions',
                'ordering': ['modified'],
            },
        ),
    ]
